import streamlit as st
from src.orchestrator import CentralOrchestrator
from src.models import OrchestratorConfig
import tempfile
import os


st.title("Executive Insight Generator")

# Ollama configuration
col1, col2 = st.columns(2)
with col1:
    ollama_url = st.text_input("Ollama URL", value="http://localhost:11434", help="Default: http://localhost:11434")
with col2:
    model_name = st.text_input("Model Name", value="qwen:0.5b", help="e.g., qwen:0.5b, qwen2.5")

uploaded = st.file_uploader("Upload CSV", type=["csv"]) 
if uploaded is not None:
    bytes_data = uploaded.read()
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".csv")
    tmp.write(bytes_data)
    tmp.flush()
    tmp.close()

    title = st.text_input("Presentation Title", value="Executive Insights")
    max_slides = st.slider("Max slides", 1, 12, 6)

    if st.button("Generate PPT"):
        cfg = OrchestratorConfig(title=title, max_slides=max_slides)
        orch = CentralOrchestrator(model=model_name, ollama_base_url=ollama_url)
        out_path = os.path.join(tempfile.gettempdir(), "insights_poc.pptx")        
        with st.spinner("Running orchestration: Loading data → Extracting insights → Polishing with Ollama → Generating PPT..."):
            pptx_path = orch.generate_ppt_from_csv(tmp.name, out_path, cfg=cfg)
        st.success("PPT generated by orchestrator with Ollama")
        with open(pptx_path, "rb") as f:
            st.download_button("Download PPTX", data=f, file_name="insights_poc.pptx")
